config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :products
  resources :invoices, only: %i(index show)
  resource :checkout, only: %i(show) do
    get 'add_product/:id', to: 'checkouts#add_product', as: :add_product
    post 'add_product', to: 'checkouts#add_product_by_code', as: :add_product_by_code
    get 'remove_product/:id', to: 'checkouts#remove_product', as: :remove_product
    get 'close_invoice', to: 'checkouts#close_invoice', as: :close_invoice
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: invoices
#
#  id         :bigint           not null, primary key
#  number     :string
#  closed     :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Invoice < ApplicationRecord
  has_many :invoice_products
  has_many :products, through: :invoice_products
  validates :number, presence: true,
                     format: { with: %r{\d{4}/[0,1,2,3]\d/\d{1,10}}i },
                     if: :closed
  validates :closed, inclusion: { in: [true, false] }
  validate :closing_with_products_validation
  validate :opening_when_closed_validation

  private

  def closing_with_products_validation
    if closed && products.empty? # rubocop:disable Style/GuardClause
      errors.add(:closed, "not possible without products assigned")
    end
  end

  def opening_when_closed_validation
    if closed_change === [true, false] # rubocop:disable Style/GuardClause, Style/CaseEquality
      errors.add(:closed, "not possible to open already closed")
    end
  end
end

app/models/invoice_product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: invoice_products
#
#  id         :bigint           not null, primary key
#  invoice_id :bigint           not null
#  product_id :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class InvoiceProduct < ApplicationRecord
  class ClosedInvoiceError < StandardError
    def message; 'Cannot add product to closed invoice'; end
  end
  belongs_to :invoice
  belongs_to :product
  before_save :prevent_adding_to_or_changing_product_in_closed_invoice

  private

  def prevent_adding_to_or_changing_product_in_closed_invoice
    raise ClosedInvoiceError if invoice.closed?
  end
end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  code       :string           not null
#  price      :decimal(8, 2)    not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#

class Product < ApplicationRecord
  acts_as_paranoid
  has_many :invoice_products
  has_many :invoices, through: :invoice_products

  after_initialize :init
  before_validation :format_before_validation

  validates :name,  presence: true,
                    uniqueness: true
  validates :code,  presence: true,
                    uniqueness: true,
                    format: {
                      with: /\A^[a-z0-9]+$\z/,
                      message: 'must be alphanumeric'
                    }
  validates :price, presence: true,
                    numericality: { greater_than: 0.0 }

  private

  def init
    return unless new_record?

    self.price ||= 9999.0
  end

  def format_before_validation
    self.code = code.try(:downcase) # Ensure downcase code
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :store_back_url
  helper_method :current_invoice, :stored_invoice_id

  private

  def store_back_url
    session[:back_url] = request.referer
  end

  def stored_invoice_id
    session[:invoice_id] = session[:invoice_id] || EnsureCurrentInvoice.call.result.id
  end

  def current_invoice
    @current_invoice ||= EnsureCurrentInvoice.call(id: stored_invoice_id).result
                                             .then { |i| InvoiceDecorator.new(i) }
  end
end

app/controllers/checkouts_controller.rb
# frozen_string_literal: true

class CheckoutsController < ApplicationController
  expose :invoice, -> { current_invoice }
  expose :product, -> { ProductQuery.new.relation.find_by(id: params[:id]) }

  def show; end

  def close_invoice
    if CloseInvoice.call(invoice, session: session).result
      flash[:success] = "Checkout successfully closed!"
    else
      flash[:error] = "Something went wrong"
    end
    redirect_to root_path
  end

  def add_product
    AddProductToInvoice.call(product, invoice_id: invoice.id).result
  end

  def add_product_by_code
    product = ProductQuery.new.find_by_code(params.dig(:product, :code))
    AddProductToInvoice.call(product, invoice_id: invoice.id).result
  end

  def remove_product
    RemoveProductFromInvoice.call(product, invoice_id: invoice.id).result
  end
end

app/controllers/invoices_controller.rb
# frozen_string_literal: true

class InvoicesController < ApplicationController
  expose :invoices, -> {
    InvoiceQuery.new.all_with_total_price.map { |i| InvoiceDecorator.new(i) }
  }
  expose :invoice, decorate: ->(i){ InvoiceDecorator.new(i) }

  def index; end

  def show; end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  expose :products, -> { ProductQuery.new.relation.all }
  expose :product, scope: -> { ProductQuery.new.relation },
                   find: ->(id, scope) { scope.find(id) }

  def inde; end

  def show; end

  def new; end

  def create
    if product.save
      flash[:success] = "Product successfully created"
      redirect_to product
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit; end

  def update
    if product.update_attributes(product_params)
      flash[:success] = "Product '%s' was successfully updated" % product.name
      redirect_to product
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if product.destroy
      flash[:success] = 'Product was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to products_url
  end

  private

  def product_params
    params.require(:product).permit(:name, :code, :price)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def action_class
    ['box', params[:controller], params[:action]].join('-')
  end

  def present(model_obj, presenter: nil)
    # Usage:
    # present(@product) do |p|
    #   %h1= p.title
    #   %h2= p.price
    # end
    presenter_klass = "#{presenter || model_obj.class}Presenter"
                      .gsub('Decorator', '')
                      .constantize
    presenter_obj = presenter_klass.new(model_obj, self)
    block_given? ? yield(presenter_obj) : presenter_obj
  end

  # rubocop:disable Naming/UncommunicativeMethodParamName
  def back_url(or: nil)
    # Use truly previous url from session or use passed
    same_place = session[:back_url] == request.original_url
    same_place ? binding.local_variable_get(:or) : session[:back_url]
  end
  # rubocop:enable Naming/UncommunicativeMethodParamName

  def render_flash
    levels = {
      notice: 'alert-info',
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-danger'
    }
    alert_html = <<-HTML
      <div class='alert %s alert-dismissible show fade'>
        %s
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    HTML

    flash.map { |k, v| alert_html % [levels[k.to_sym], v] }
         .join
         .then { |alerts| "<div class='alerts'>#{alerts}</div>".html_safe }
  end
end

app/helpers/invoices_helper.rb
# frozen_string_literal: true

module InvoicesHelper
  def current_invoice?
    [params[:controller], params[:id]] === ["invoices", stored_invoice_id.to_s] # rubocop:disable  Style/CaseEquality
  end
end

app/views/checkouts/add_product.js.erb
if ($('.box-invoices-show, .box-checkouts-show').length > 0) {
  Turbolinks.clearCache();
  Turbolinks.visit(location.toString());
} else {
  $('.bar-total-price').text('<%= present(invoice).total_price_text %>')
}

app/views/checkouts/add_product_by_code.js.erb
if ($('.box-invoices-show, .box-checkouts-show').length > 0) {
  Turbolinks.clearCache();
  Turbolinks.visit(location.toString());
} else {
  $('.bar-total-price').text('<%= present(invoice).total_price_text %>')
}

app/views/checkouts/remove_product.js.erb
if ($('.box-invoices-show, .box-checkouts-show').length > 0) {
  Turbolinks.clearCache();
  Turbolinks.visit(location.toString());
} else {
  $('.bar-total-price').text('<%= present(invoice).total_price_text %>')
}

app/views/checkouts/show.html.haml
- present(invoice) do |i|
  %h1 Checkout
  %hr/
  %table.table
    %tr
      %th{:scope => "col"} Name
      %th{:scope => "col"} Unit price
      %th{:scope => "col"} Count
      %th{:scope => "col"} Sum
    - i.products_summary.each do |product|
      - present(product) do |p|
        %tr
          %td= p.name
          %td= p.price
          %td= p.qty
          %td= p.price
    %tr
      %td
      %td
      %td
        %strong Total:
      %td= i.total_price
%hr/
.float-left
  = link_to("Back", back_url(or: root_path), class: 'back-link')
.float-right
  = link_to("Close invoice", close_invoice_checkout_path, class: 'back-link text-right')

app/views/invoices/_add_to_invoice_form.html.haml
= simple_form_for(:product, url: add_product_by_code_checkout_path(i), remote: true, html: { class: 'form-inline'}) do |f|
      = f.input :code, required: true, input_html: { class: 'uppercase mr-3' }, label: false
      = f.button :submit, value: 'Add product by code', class: 'btn-primary'

app/views/invoices/_show_current.html.haml
%table.table
  %tr
    %th{:scope => "col"} Name
    %th{:scope => "col"} Unit price
    %th{:scope => "col"} Count
    %th{:scope => "col"} Sum
    %th{:scope => "col"}
    %th{:scope => "col"}
  - i.products_summary.each do |product|
    - present(product) do |p|
      %tr
        %td= p.name
        %td= p.price
        %td= p.qty
        %td= p.price
        %td= link_to("+", add_product_checkout_path(p), remote: true)
        %td= link_to("-", remove_product_checkout_path(p), remote: true)
  %tr
    %td
    %td
    %td
      %strong Total:
    %td= i.total_price
    %td
    %td

.col-12
  .ml-auto
    = render partial: 'add_to_invoice_form', locals: { i: i }

app/views/invoices/_show_default.html.haml
- present(invoice) do |i|
  %table.table
    %tr
      %th{:scope => "col"} Name
      %th{:scope => "col"} Unit price
      %th{:scope => "col"} Count
      %th{:scope => "col"} Sum
    - i.products_summary.each do |product|
      - present(product) do |p|
        %tr
          %td= p.name
          %td= p.price
          %td= p.qty
          %td= p.price
    %tr
      %td
      %td
      %td
        %strong Total:
      %td= i.total_price

app/views/invoices/index.html.haml
%h1.d-sm-inline-block Invoices

%table.table
  %tr
    %th{:scope => "col"} #
    %th{:scope => "col"} Created at
    %th{:scope => "col"} Number
    %th{:scope => "col"} Total
    %th{:scope => "col"} Closed
    %th{:scope => "col"}
  - invoices.each do |invoice|
    - present(invoice) do |i|
      %tr
        %th{:scope => "row"}=i.id
        %td= i.created_at
        %td= link_to(i.number, invoice_path(i))
        %td= i.total_price
        %td= i.closed?
        %td= link_to("Show", invoice_path(i))

app/views/invoices/show.html.haml
- present(invoice) do |i|
  - if i.closed?
    %span.text-danger Invoice closed
    %h6
      %strong Number:
      = i.number
  %h1 Invoice summary
  %hr/
  - if current_invoice?
    = render partial: 'show_current', locals: { i: i }
  - else
    = render partial: 'show_default', locals: { i: i }
%hr/
= link_to("Back", back_url(or: invoices_path), class: 'back-link')
- if current_invoice?
  |
  = link_to("Checkout", checkout_path, class: 'back-link text-right')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SimpleInvoiceRB
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render_flash
    %nav.navbar.navbar-expand-md.navbar-light.fixed-top{style: "background-color: #e3f2fd;"}
      %a.navbar-brand{:href => "/"} SimpleInvoiceRB
      %button.navbar-toggler{"aria-controls" => "navbarsExampleDefault", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExampleDefault", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarsExampleDefault.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item.active
            = link_to root_path, class: 'nav-link' do
              Home
              %span.sr-only (current)
          %li.nav-item.dropdown
            %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"} Products
            .dropdown-menu{"aria-labelledby" => "dropdown01"}
              = link_to 'All (list)', products_path, class: 'dropdown-item'
              = link_to 'Add new', new_product_path, class: 'dropdown-item'
          %li.nav-item.dropdown
            %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"} Invoices
            .dropdown-menu{"aria-labelledby" => "dropdown01"}
              = link_to 'All (list)', invoices_path, class: 'dropdown-item'
        %ul.navbar-nav.ml-auto.mr-3
          %li
            = link_to checkout_path, class: 'bar-total-price' do
              = present(current_invoice).total_price_text
    %main.container{:role => "main"}
      .container{class: "#{action_class}"}
        = yield

app/views/products/_form.html.haml
%h1= headline
%hr/
.col-md-6
  = simple_form_for product do |f|
    = f.input :name, required: true
    = f.input :code, required: true, input_html: { class: 'uppercase' }
    = f.input :price, as: :decimal, required: true, wrapper: :input_group, append: t('number.currency.format.unit'), input_html: { type: 'number', step: '0.01', min: '0' }
    = f.button :submit, class: 'btn-primary'
    or
    = link_to("Back", back_url(or: products_path), class: 'back-link')

app/views/products/edit.html.haml
= render partial: 'form', locals: {headline: 'Edit'}

app/views/products/index.html.haml
%h1.d-sm-inline-block Products
= link_to("Create Product", new_product_path, class: 'btn btn-primary float-sm-right')
%hr/

%table.table
  %tr
    %th{:scope => "col"} #
    %th{:scope => "col"} Name
    %th{:scope => "col"} Code
    %th{:scope => "col"} Price
    %th{:scope => "col"}
    %th{:scope => "col"}
    %th{:scope => "col"}
    %th{:scope => "col"}
  - products.each do |product|
    - present(product) do |p|
      %tr
        %th{:scope => "row"}=p.id
        %td= link_to(p.name, product_path(p))
        %td= p.code
        %td= p.price
        %td= link_to("Add invoice", add_product_checkout_path(p), remote: true)
        %td= link_to("Show", product_path(p))
        %td= link_to("Edit", edit_product_path(p))
        %td= link_to("Destroy", p, method: :delete, remote: true, data: { confirm: 'Are you sure?' })

app/views/products/new.html.haml
= render partial: 'form', locals: {headline: 'New'}

app/views/products/show.html.haml
- present(product) do |p|
  %h1= "Product: #{p.name}"
  %hr/
  %table
    %tr
      %td
        %b Name:
        = p.name
    %tr
      %td
        %b Code:
        = p.code
    %tr
      %td
        %b Price:
        = p.price
%hr/
= link_to("Edit", edit_product_path(product))
|
= link_to("Back", back_url(or: products_path), class: 'back-link')